version: "3.8"
networks:
  app-network:
    driver: bridge
volumes:
  minio-data:  # Define the 'minio-data' volume
services:
  webserver:
    image: "nginx"
    container_name: "nginx_${APP_NAME}"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/config/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql_db
    networks:
      - app-network
  mysql_db:
    image: mysql:5.7
    container_name: mysql_${APP_NAME}
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "mysql_${APP_NAME}"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network
  # redis:
  #   image: redis:latest
  #   container_name: redis_${APP_NAME}
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  minio:
    image: bitnami/minio:latest
    container_name: minio_${APP_NAME}
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data  # Volume for Minio data

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_${APP_NAME}
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php_${APP_NAME}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    # ports:
    #   - "9000:9000"
  composer:
    image: "composer:latest"
    container_name: composer_${APP_NAME}
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
