version: "3.8"
networks:
  app-network:
    driver: bridge
services:
  webserver:
    image: "nginx"
    container_name: "nginx_${APP_NAME}"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/config/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql_db
    networks:
      - app-network
  mysql_db:
    image: mysql:5.7
    container_name: mysql_${APP_NAME}
    restart: unless-stopped
    ports:
      - "3308:3306"
    # environment:
    #   MYSQL_ROOT_PASSWORD: password
    #   MYSQL_DATABASE: "mysql_${APP_NAME}"
    #   MYSQL_USER: dev
    #   MYSQL_PASSWORD: password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "mysql_${APP_NAME}"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_${APP_NAME}
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php_${APP_NAME}
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    ports:
      - "9000:9000"
  composer:
    image: "composer:latest"
    container_name: composer_${APP_NAME}
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
